FROM sdx-base AS base

ARG NODE_VERSION

WORKDIR /opt

RUN curl https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz | tar xfJ -

ENV PATH="/opt/node-${NODE_VERSION}-linux-x64/bin:$PATH"