ARG BASE_VERSION

FROM sdx-base:${BASE_VERSION} AS base

ARG NODE_VERSION

WORKDIR /opt

RUN ["/usr/bin/env", "bash", "-c", "set -o pipefail && curl https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz | tar xfJ -"]

ENV PATH="/opt/node-${NODE_VERSION}-linux-x64/bin:$PATH"
